config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  devise_for :users
  get 'root/index'

  root to: 'root#index'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  include ActiveModel::Dirty

  belongs_to :invoice

  validates_presence_of :amount, :invoice

  after_save :recalculate_invoice_expenses

  # def balance unit_count, unit_price, vat_price
  # @param [Remote::Billapp::Invoice::Line] il
  def balance il
    counting_result = (
      ( il.quantity * il.unit_price ) * ( ( il.vat / 100 ) + 1.0 )
    ) - amount

    counting_result.ceil(1)
  end

  private

  def recalculate_invoice_expenses
    invoice.recalculate_expenses
  end
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_one :remote_invoice, class_name: 'Remote::Billapp::Invoice'
  has_many :expenses

  validates_presence_of   :ba_id, :ba_number
  validates_uniqueness_of :ba_id, :ba_number

  accepts_nested_attributes_for :expenses

  def recalculate_expenses
    self.reload
    self.total_expenses = expenses.inject(0.0) do |memo, expense|
      memo += expense.amount

      memo
    end

    self.save
  end
end

app/models/remote/billapp/base.rb
require 'active_resource'

module Remote
  module Billapp
    class Base < ActiveResource::Base
      self.format = :json


      # @param [User] user
      def self.set_ba_credentials user
        Remote::Billapp::Base.site = 'https://%s.billapp.cz/'%[
          user.billapp_subdomain
        ]
        Remote::Billapp::Base.user = user.billapp_username
        Remote::Billapp::Base.password = user.billapp_userpass
      end

    end
  end
end

app/models/remote/billapp/invoice.rb
module Remote
  module Billapp
    class Invoice < Base

    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_billapp_credentials?
    billapp_subdomain.present? &&
    billapp_username.present? &&
    billapp_userpass.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_ba_credentials

  private

  def set_ba_credentials
    if current_user && current_user.has_billapp_credentials?
      Remote::Billapp::Base::set_ba_credentials current_user
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :billapp_subdomain
    devise_parameter_sanitizer.for(:account_update) << :billapp_username
    devise_parameter_sanitizer.for(:account_update) << :billapp_userpass
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.has_billapp_credentials?
      @invoices = Remote::Billapp::Invoice.all
    end
  end

  def edit
    begin
      @remote_invoice = Remote::Billapp::Invoice.find params[:id]
      @invoice = Invoice.find_by(ba_id: @remote_invoice.id)

      unless @invoice
        @invoice = Invoice.create!(
            ba_id:      @remote_invoice.id,
            ba_number:  @remote_invoice.number
          )

        # These two operations are separated for better debugging and
        #   readability
        @invoice.expenses = @remote_invoice.lines.map.with_index do |il, index|
          Expense.create! amount:   0,
                          ba_index: index,
                          invoice:  @invoice
        end
      end

      @invoice.reload

      @local_expenses = @invoice.expenses.inject([]) do |memo, expense|
        memo[expense.ba_index] = expense

        memo
      end
    rescue ActiveResource::ResourceNotFound
      redirect_to invoices_path, error: t('.invoice_not_found')
    end
  end

  def update
    local_invoice = Invoice.find params[:id]

    if local_invoice.update(invoice_params)
      redirect_to :back, notice:  t('update_success')
    else
      redirect_to :back, alert:   t('update_error')
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:id, expenses_attributes: [:id, :amount])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # @param [String] app_label
  def bootstrap_label_class app_label
    { 'notice' => 'success',
      'alert' => 'danger'
    }[app_label] || app_label
  end
end

app/helpers/invoice_helper.rb
module InvoiceHelper
  def balance_class balance
    if balance > 0
      'balance-good'
    elsif balance < 0
      'balance-bad'
    end
  end
end

app/views/application/_flashes.html.slim
#flash
  - flash.each do |key, value| 
    div id="flash-#{ key }"
      span class="label label-#{bootstrap_label_class(key)}"
        = value

app/views/application/_user_nav.html.slim
ul.nav.navbar-nav
  - if user_signed_in?
    li
      = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    li
      a href=new_user_session_path Sign in

app/views/invoices/_invoices_list.html.slim
table.table.table-striped.table-condensed.table-hover
  thead
    tr
      th Number

  tbody
    - @invoices.each do |invoice|
      tr
        td
          a href=edit_invoice_path(id: invoice.id) = invoice.number

app/views/invoices/edit.html.slim
h1 = t '.heading', invoice_nr: @remote_invoice.number

/= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
= simple_form_for(@invoice, url: invoice_path(@invoice), html: { method: :put }) do |f|
  - if @remote_invoice.lines.count > 10
    .form-actions
      = f.button :submit, 'Update', class: 'btn-primary'

  table.table.table-striped.table-condensed.table-hover
    thead
      tr
        th Description
        th Quantity
        th Unit price
        th VAT
        th Expenses
        th Balance

    tbody
      - @remote_invoice.lines.each_with_index do |il, index|
        tr class=balance_class(@local_expenses[index].balance(il))
          td = il.description
          td = il.quantity
          td = il.unit_price
          td = "#{il.vat} %"
          td
            .form-group.password.optional.user_password
              input name="invoice[expenses_attributes][][id]" type="hidden" value=@local_expenses[index].id
              input#user_password.password.optional.form-control name="invoice[expenses_attributes][][amount]" type="text" value=@local_expenses[index].amount
          td
            = @local_expenses[index].balance(il)

    tfoot
      tr
        td colspan='6' &nbsp;
      tr
        th colspan='5' Total income
        td = @remote_invoice.total_amount

      tr
        th colspan='5' Total expenses
        td = @invoice.total_expenses

  .form-actions
    = f.button :submit, 'Update', class: 'btn-primary'

app/views/invoices/index.html.slim
h1 = t '.heading'

- if @invoices
  = render 'invoices_list'
- else
  ' Please fill up your Billapp credentials.
  a href=edit_user_registration_path User form

app/views/layouts/application.html.slim
doctype html
html
  head
    title= page_title
    meta charset="utf-8"
    = stylesheet_link_tag :application, media: 'all'
    = csrf_meta_tags

  body class=body_class

    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand ProfitAndLost

        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              a href=invoices_path Invoices

          .navbar-right
            = render 'application/user_nav'



    .container
      = render 'application/flashes'

      = yield

    = javascript_include_tag :application
    = yield :javascript

app/views/root/index.html.slim
h1 = t '.heading'
p = t '.welcome_text'